const {
  findAdresse,
  getCommunes,
  getDataFromGouvFr,
  _httpCallAuthenticated,
  _setDraggable,
  _setupTagger,
  _getPlatformServices,
  _setDroppable,
  _3DSpace_get_docInfo,
  _3DSpace_csrf,
  _3DSpace_get_csrf,
  _3DSpace_file_url,
  _3DSpace_file_url_csr,
  _3DSpace_file_update,
  _3DSpace_file_update_csr,
  _3DSpace_Create_Doc,
  _3DSpace_get_securityContexts,
  _3DSpace_download_doc,
  _3DSpace_download_multidoc,
} = require("./plateform/index");

module.exports = {
  findAdresse,
  getCommunes,
  getDataFromGouvFr,
  _httpCallAuthenticated,
  _setDraggable,
  _setupTagger,
  _getPlatformServices,
  _setDroppable,
  _3DSpace_get_docInfo,
  _3DSpace_csrf,
  _3DSpace_get_csrf,
  _3DSpace_file_url,
  _3DSpace_file_url_csr,
  _3DSpace_file_update,
  _3DSpace_file_update_csr,
  _3DSpace_Create_Doc,
  _3DSpace_get_securityContexts,
  _3DSpace_download_doc,
  _3DSpace_download_multidoc,
};
