import { UUID } from "./lib/api/index";
import { couleurs } from "./lib/gouv/colors";
import {
  findAdresse,
  getCommunes,
  getDataFromGouvFr,
} from "./lib/gouv/gouv_api";
import { updateEvent, chunkArray } from "./lib/utils";
import { compass_getListAdditionalApps } from "./lib/plateform/Compass";
import {
  _getMe,
  _setDraggable,
  _setDroppable,
  _getServiceUrl,
  _getPlatformServices,
  _getServiceUrl_3DPassport,
  _getPlateformInfos,
  _httpCallAuthenticated,
  _setupTagger,
} from "./lib/plateform/main/3dexperience_api";
import {
  _AppMngt_get_users,
  _AppMngt_get_info_user,
} from "./lib/plateform/main/3dcompass_api";
import {
  createUserGroups,
  getComplementUG,
  getUsersGroupRules,
  getUserGroupsList,
  deleteUserGroups,
  patchUserGroups,
  patchUserGroupsControl,
  readUserGroupControl,
  getUserGroupsByURIList,
  getUserGroupsByEmailList,
} from "./lib/plateform/Usersgroup";

import {
  _3DSpace_get_docInfo,
  _3DSpace_get_multiDocInfo,
  _3DSpace_get_csrf,
  _3DSpace_csrf,
  _3DSpace_get_ticket,
  _3DSpace_file_url_csr,
  _3DSpace_file_update,
  _3DSpace_file_update_csr,
  _3DSpace_Upload_File,
  _3DSpace_Create_Doc,
  _3DSpace_Update_Doc,
  _3DSpace_get_securityContexts,
  _3DSpace_download_doc,
  _3DSpace_download_multidoc,
  _3DSpace_get_downloadTicket_multidoc,
  _3DSpace_lifecycle_getNextStates,
  _3DSpace_lifecycle_changeState,
  _3DSpace_lifecycle_getGraph,
  _3DSpace_lifecycle_getRevisions,
  _3DSpace_lifecycle_getNextRevision,
  _3DSpace_lifecycle_changeRevision,
  _3DSpace_bookmark_addSubsciptions,
  _3DSpace_bookmark_newWorkspace,
  _3DSpace_put_docInfo,
} from "./lib/plateform/main/3dspace_api";

import { getCSRFToken } from "./lib/plateform/main/getCSRFToken";
import { getAllContextSecurity } from "./lib/plateform/main/getCTX";
import { getDataFrom3DSpace } from "./lib/plateform/main/getDataFrom3DSpace";
import { getDownloadDocument } from "./lib/plateform/main/getDownloadDocument";
import { pushDataIn3DSpace } from "./lib/plateform/main/pushDataIn3DSpace";
import {
  getDatasFrom3DSpace,
  dataMixing,
  getDatasByTenant,
  get_3DSpace_csrf,
} from "./lib/plateform/main/loadDatas";
import {
  getInfoDocTags,
  removeTagToDoc,
  addTagToDoc,
} from "./lib/plateform/Tag";
import {
  _3DSwym_getAllCommunities,
  _3DSwym_getMembersCommunity,
  _3DSwym_getIdeaStatusMaturity,
  _3DSwym_buildDirectMessage,
  _3DSwym_findCommunityToInstantMSG,
  _3DSwym_sendMessageData,
} from "./lib/plateform/Swym/communauty";
import {
  _3DSwym_postIdeaTemplate,
  _3DSwym_deleteIdea,
  _3DSwym_getOneIdea,
  _3DSwym_getAllListIdeas,
  _3DSwym_editIdea,
  _3DSwym_postIdea,
  _3DSwym_ForwardIdea,
} from "./lib/plateform/Swym/idea";
import {
  _3DSwym_get_currentUser,
  _3DSwym_get_findUser,
} from "./lib/plateform/Swym/user";
import { _3DSwym_addComment } from "./lib/plateform/Swym/comment";
import {
  _3DSwym_get_Token,
  _3DSwym_getAllNews,
  _3DSwym_getFamiliarPeople,
} from "./lib/plateform/Swym/3dswym_api";
import {
  _Iterop_Auth_CAS,
  _Iterop_jwtUser,
  _getServiceUrl_Iterop,
  _Iterop_getAllBusinessTables,
  _Iterop_runProcess,
  _Iterop_AddOrRemoveRows,
  _Iterop_getOneBusinessTable,
  _Iterop_getOneBusinessTableRows,
  _Iterop_businessTableSearchInRows,
  _Iterop_createBusinessTable,
  _Iterop_updateBusinessTable,
  _Iterop_GetOneDependencyTable,
  _Iterop_PatchDependencyTable,
  _Iterop_PutDependencyTable,
  _Iterop_GetOneList,
} from "./lib/plateform/main/iterop_apiv2";

import { sayHello } from "./lib/add/index"; //Pour tester de la librairie

import { _3DSearch_usersGroup } from "./lib/plateform/Search/index";

export {
  _3DSpace_Create_Doc,
  _3DSpace_Update_Doc,
  _3DSpace_csrf,
  _3DSpace_download_doc,
  _3DSpace_download_multidoc,
  _3DSpace_file_update_csr,
  _3DSpace_Upload_File,
  _3DSpace_file_update,
  _3DSpace_file_url_csr,
  _3DSpace_get_ticket,
  _3DSpace_get_csrf,
  _3DSpace_get_docInfo,
  _3DSpace_put_docInfo,
  _3DSpace_get_multiDocInfo,
  _3DSpace_get_downloadTicket_multidoc,
  _3DSpace_get_securityContexts,
  _3DSpace_lifecycle_changeRevision,
  _3DSpace_lifecycle_changeState,
  _3DSpace_lifecycle_getGraph,
  _3DSpace_lifecycle_getRevisions,
  _3DSpace_lifecycle_getNextRevision,
  _3DSpace_lifecycle_getNextStates,
  _3DSpace_bookmark_addSubsciptions,
  _3DSpace_bookmark_newWorkspace,
  _3DSearch_usersGroup,
  _3DSwym_getAllCommunities,
  _3DSwym_getMembersCommunity,
  _3DSwym_buildDirectMessage,
  _3DSwym_deleteIdea,
  _3DSwym_findCommunityToInstantMSG,
  _3DSwym_getAllListIdeas,
  _3DSwym_get_currentUser,
  _3DSwym_get_findUser,
  _3DSwym_get_Token,
  _3DSwym_getAllNews,
  _3DSwym_getFamiliarPeople,
  _3DSwym_getIdeaStatusMaturity,
  _3DSwym_getOneIdea,
  _3DSwym_editIdea,
  _3DSwym_postIdea,
  _3DSwym_postIdeaTemplate,
  _3DSwym_ForwardIdea,
  _3DSwym_sendMessageData,
  _3DSwym_addComment,
  _getServiceUrl_Iterop,
  _Iterop_Auth_CAS,
  _Iterop_jwtUser,
  _Iterop_getAllBusinessTables,
  _Iterop_getOneBusinessTable,
  _Iterop_getOneBusinessTableRows,
  _Iterop_businessTableSearchInRows,
  _Iterop_createBusinessTable,
  _Iterop_updateBusinessTable,
  _Iterop_GetOneDependencyTable,
  _Iterop_PatchDependencyTable,
  _Iterop_PutDependencyTable,
  _Iterop_GetOneList,
  _Iterop_runProcess,
  _Iterop_AddOrRemoveRows,
  _AppMngt_get_info_user,
  _AppMngt_get_users,
  _getMe,
  _getPlateformInfos,
  _getServiceUrl,
  _getPlatformServices,
  _getServiceUrl_3DPassport,
  _httpCallAuthenticated,
  _setDraggable,
  _setDroppable,
  _setupTagger,
  addTagToDoc,
  compass_getListAdditionalApps,
  couleurs,
  createUserGroups,
  dataMixing,
  deleteUserGroups,
  findAdresse,
  get_3DSpace_csrf,
  getAllContextSecurity,
  getCommunes,
  getComplementUG,
  getCSRFToken,
  getDataFrom3DSpace,
  getDataFromGouvFr,
  getDatasByTenant,
  getDatasFrom3DSpace,
  getDownloadDocument,
  getInfoDocTags,
  getUserGroupsList,
  getUserGroupsByURIList,
  getUserGroupsByEmailList,
  getUsersGroupRules,
  patchUserGroups,
  patchUserGroupsControl,
  pushDataIn3DSpace,
  readUserGroupControl,
  removeTagToDoc,
  sayHello, // fonction de test
  updateEvent,
  UUID,
  chunkArray,
};
